# NOTE: Generated By HttpRunner v3.1.11
# FROM: testcases\params_csv.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from api.login_test import TestCaseLogin as Login

from api.get_user_test import TestCaseGetUser as GetUser

from api.logout_test import TestCaseLogout as Logout


class TestCaseParamsCsv(HttpRunner):
    @pytest.mark.parametrize("param", Parameters({"user": "${P(user.csv)}"}))
    def test_start(self, param):
        super().test_start(param)

    config = Config("登录接口 测试用例").base_url("${ENV(base_url)}").export(*["token"])

    teststeps = [
        Step(RunTestCase("登录接口 测试用例").call(Login).export(*["token"])),
        Step(RunTestCase("获取指定用户信息 测试用例").call(GetUser).export(*["token"])),
        Step(RunTestCase("退出登录 测试用例").call(Logout).export(*["token"])),
    ]


if __name__ == "__main__":
    TestCaseParamsCsv().test_start()
