# NOTE: Generated By HttpRunner v3.1.11
# FROM: api\get_user.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetUser(HttpRunner):

    config = Config("获取指定用户信息接口").base_url("${ENV(base_url)}").export(*["token"])

    teststeps = [
        Step(
            RunRequest("获取指定用户信息接口 测试用例")
            .get("/users/$user")
            .with_headers(**{"Authorization": "Bearer $token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseGetUser().test_start()
