# NOTE: Generated By HttpRunner v3.1.11
# FROM: api\logout.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogout(HttpRunner):

    config = Config("退出登录接口").base_url("${ENV(base_url)}").export(*["token"])

    teststeps = [
        Step(
            RunRequest("退出登录接口 测试用例")
            .post("/users/logout")
            .with_headers(**{"Authorization": "Bearer $token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogout().test_start()
